# Generated by Django 2.2.2 on 2019-07-21 09:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190720_2006'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
